name: Simple Test Action

on:
  workflow_dispatch:  # this means you can run it manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3000396@ds.study.iitm.ac.in
        run: echo "Hello, world!"
